project_name: terraform-log-exporter
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
builds:
  - binary: terraform-log-exporter
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - name_template: "{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
release:
  github:
    owner: kapetacom
    name: terraform-log-exporter

nfpms:
  - id: terraform-log-exporter
    maintainer: 'Kapeta <info@kapeta.com>'
    description: terraform-log-exporter is a tool to forwards logs from terraform to a log server
    package_name: terraform-log-exporter
    formats:
      - apk
      - deb
      - rpm
  - rpm:
     summary: terraform-log-exporter is a tool forwards logs from terraform to a log server